### ISSUE TITLE
Using formattable column names are printing column values?

### ISSUE THREAD

**Issue by MayaGans** [schaffman5/rtf#1]
Hi! I firstly wanted to thank you for this wonderful package! I'm trying to print a dataframe as RTF which I've converted for formatting using `formattable` and the values within the columns are correct but the column names are now printing the column values (ie "c(1,2,3)"  instead of the title of the column). Any thoughts on how to mitigate this?

```
library(formattable)
library(rtf)

dummy <- data.frame(l = c(1,2,3), x = c("a", "b", "c"))
dummy <- formattable(dummy)
rtffile <- RTF("file.doc")
addTable(rtffile, dummy)
done(rtffile)
```

**Comment by schaffman5** [comment]
I'm not sure what is accomplished with the formattable function, but the mitigation is to not use that function before addTable.  Alternatively, if formattable is doing something useful, you'll need to force the dummy variable back to a pure data.frame before calling addTable, e.g.  

```
library(formattable)
library(rtf)

dummy <- data.frame(l = c(1,2,3), x = c("a", "b", "c"))
dummy <- as.data.frame(formattable(dummy))
rtffile <- RTF("file.doc")
addTable(rtffile, dummy)
done(rtffile)
```
